version: '2.6'

services:
    # 
    zoo1:
        image: wurstmeister/zookeeper
        restart: unless-stopped
        ports:
            - "2181:2181"
        container_name: zookeeper

    # kafka 
    kafka1:
        image: wurstmeister/kafka
        ports:
            - "11037:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: '139.159.202.227'
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
            KAFKA_ADVERTISED_PORT: 11037
            KAFKA_BROKER_ID: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CREATE_TOPICS: "stream-in:2:1,stream-out:2:1"
        depends_on:
            - zoo1
        container_name: kafka